//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Acceso BBDD Cuenta.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Acceso_BBDD_Cuenta implements IGestionCuentasBBDD
{
  /** */
  public void InsertCuenta()
  {
  
  }
  
  /** */
  public void DeleteCuenta()
  {
  
  }
  
  /** */
  public void SelectCuenta()
  {
  
  }
}
