//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Administrador Comunidad.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Administrador_Comunidad extends Comunidad implements IComunidad_Admin
{
  /** */
  public void Expulsar_Miembro()
  {
  
  }
  
  /** */
  public void Dar_Permiso_Administrador()
  {
  
  }
  
  /** */
  public void Quitar_Permiso_Administrador()
  {
  
  }
  
  /** */
  public void Aceptar_Peticion_Miembro()
  {
  
  }
  
  /** */
  public void Borrar_Comunidad()
  {
  
  }
  
  /** */
  public void Notificar_Administrador_Cuenta_Creada()
  {
  
  }
}
