import java.util.ArrayList;
import java.util.Scanner;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Comentario.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




public class Comentario implements IComentario
{
	
  Scanner scan = new Scanner(System.in);
  /** */
  private String contenido;
  
  /** */
  private ArrayList <Comentario> respuestas;
  
  /** */
  private Cuenta cuenta;
  
  /** */
  public Cuenta escribe_Comentario;
  
  
  
  
  /** */
  public Comentario(String contenido)
  {
	  
	  this.contenido = scan.nextLine();
	  this.respuestas = new ArrayList<Comentario>();
	  //this.cuenta = new Cuenta();
	  //this.escribe_Comentario = new Cuenta();
	  
  }
  
  
  public void Mostrar()
  {
  
  }
  
  /** */
  public void Borrar()
  {
  
  }
  
  /** */
  public void Subir_comentario()
  {
  
  }
  
  /** */
  public void AñadirRespuesta(Comentario respuesta)
  {
  
  }
  
  /** */
  public void EliminarRespuesta(Comentario respuesta)
  {
  
  }
  
  /** */
  public void BorradoCascadaRespuestas()
  {
  
  }
  
  /** */
  public void AñadirCuenta(Cuenta cuenta)
  {
  
  }
  
  
  
  /** */
  public void EliminarCuenta()
  {
  
  }

@Override
public void SubirComentario() {
	// TODO Auto-generated method stub
	
}


public String getContenido() {
	return contenido;
}


public void setContenido(String contenido) {
	this.contenido = contenido;
}


public ArrayList<Comentario> getRespuestas() {
	return respuestas;
}


public void setRespuestas(ArrayList<Comentario> respuestas) {
	this.respuestas = respuestas;
}


public Cuenta getCuenta() {
	return cuenta;
}


public void setCuenta(Cuenta cuenta) {
	this.cuenta = cuenta;
}


public Cuenta getEscribe_Comentario() {
	return escribe_Comentario;
}


public void setEscribe_Comentario(Cuenta escribe_Comentario) {
	this.escribe_Comentario = escribe_Comentario;
}
}
