import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Comentario.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




public class Comentario implements IComentario
{
  /** */
  private String Contenido;
  
  /** */
  private ArrayList <Comentario> Respuestas;
  
  /** */
  private Cuenta Cuenta;
  
  /** */
  public Cuenta Escribe_Comentario;
  
  
  
  
  /** */
  public Comentario(String contenido)
  {
  
  }
  
  
  public void Mostrar()
  {
  
  }
  
  /** */
  public void Borrar()
  {
  
  }
  
  /** */
  public void Subir_comentario()
  {
  
  }
  
  /** */
  public void AñadirRespuesta(Comentario respuesta)
  {
  
  }
  
  /** */
  public void EliminarRespuesta(Comentario respuesta)
  {
  
  }
  
  /** */
  public void BorradoCascadaRespuestas()
  {
  
  }
  
  /** */
  public void AñadirCuenta(Cuenta cuenta)
  {
  
  }
  
  
  
  /** */
  public void EliminarCuenta()
  {
  
  }

@Override
public void SubirComentario() {
	// TODO Auto-generated method stub
	
}


public String getContenido() {
	return Contenido;
}


public void setContenido(String contenido) {
	Contenido = contenido;
}


public ArrayList<Comentario> getRespuestas() {
	return Respuestas;
}


public void setRespuestas(ArrayList<Comentario> respuestas) {
	Respuestas = respuestas;
}


public Cuenta getCuenta() {
	return Cuenta;
}


public void setCuenta(Cuenta cuenta) {
	Cuenta = cuenta;
}


public Cuenta getEscribe_Comentario() {
	return Escribe_Comentario;
}


public void setEscribe_Comentario(Cuenta escribe_Comentario) {
	Escribe_Comentario = escribe_Comentario;
}
}
