import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Comunidad.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Comunidad implements IComunidad, IComunidad_Admin
{
  /** */
  private ArrayList<Cuenta> Miembros;
  
  /** */
  private ArrayList<String> Mensajes;
  
  /** */
  private ArrayList <String> Peticiones_Union;
  
  /** */
  private Cuenta Administrador;
  
  /** */
  public void Añadir_Mensaje()
  {
  
  }
  
  /** */
  public void Mostrar_Mensajes()
  {
  
  }

@Override
public void Expulsar_Miembro() {
	// TODO Auto-generated method stub
	
}

@Override
public void Dar_Permiso_Administrador() {
	// TODO Auto-generated method stub
	
}

@Override
public void Quitar_Permiso_Administrador() {
	// TODO Auto-generated method stub
	
}

@Override
public void Aceptar_Peticion_Miembro() {
	// TODO Auto-generated method stub
	
}

@Override
public void Borrar_Comunidad() {
	// TODO Auto-generated method stub
	
}

@Override
public void Notificar_Administrador_Comunidad_Creada() {
	// TODO Auto-generated method stub
	
}

public ArrayList<Cuenta> getMiembros() {
	return Miembros;
}

public void setMiembros(ArrayList<Cuenta> miembros) {
	Miembros = miembros;
}

public ArrayList<String> getMensajes() {
	return Mensajes;
}

public void setMensajes(ArrayList<String> mensajes) {
	Mensajes = mensajes;
}

public ArrayList<String> getPeticiones_Union() {
	return Peticiones_Union;
}

public void setPeticiones_Union(ArrayList<String> peticiones_Union) {
	Peticiones_Union = peticiones_Union;
}

public Cuenta getAdministrador() {
	return Administrador;
}

public void setAdministrador(Cuenta administrador) {
	Administrador = administrador;
}
}
