import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cuenta.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Cuenta
{
	
  private Scanner scan = new Scanner(System.in);
  /** */
  private String correo;
  
  /** */
  private String alias;
  
  /** */
  private String contrasenia;
  
  /** */
  private ArrayList<Comunidad> comunidades;
  
  /** */
  private ArrayList<Publicacion> publicaciones;
  
  /** */
  private ArrayList<Comentario> comentarios;
  
  /** */
  private ArrayList<Cuenta> usuarios;
  
  /** */
  private Factory_Publicacion factoryPublicacion;
  
  /** */
  public Cuenta()
  {
	  this.correo = scan.nextLine();
	  this.contrasenia = scan.nextLine();
	  this.comunidades = new ArrayList<Comunidad>();
	  this.publicaciones = new ArrayList<Publicacion>();
	  this.comentarios = new ArrayList<Comentario>();
	  this.usuarios = new ArrayList<Cuenta>();
	  //this.factoryPublicacion = new Factory_Publicion();
	  
	  guardarDatos();
	  
	  
	}
  
  private void guardarDatos() {
	  
	  JSONArray comunidadesJSON = (JSONArray) this.comunidades;
	  JSONArray publicacionesJSON = (JSONArray) this.publicaciones;
	  JSONArray comentariosJSON = (JSONArray) this.comentarios;
	  JSONArray usuariosJSON = (JSONArray) this.usuarios;
	  
	  
	  JSONObject usuario = new JSONObject();
		usuario.put("alias", this.alias);
		usuario.put("correo", this.correo);
		usuario.put("contrasenia", this.contrasenia);
		usuario.put("Comunidades", comunidadesJSON);
		usuario.put("comentariosJSON", comentariosJSON);
		usuario.put("usuariosJSON", usuariosJSON);
		
		try(FileWriter file = new FileWriter("Usuarios.json")){
			file.write(usuario.toJSONString());
		}catch(IOException e) {
			e.printStackTrace();
		}
			
  }
  
  
  
  public String getCorreo() {
	return correo;
}

public void setCorreo(String correo) {
	correo = correo;
}

public String getAlias() {
	return alias;
}

public void setAlias(String alias) {
	alias = alias;
}

public String getContrasenia() {
	return contrasenia;
}

public void setContrasenia(String contrasenia) {
	contrasenia = contrasenia;
}

public Comunidad getComunidades() {
	return comunidades;
}

public void setComunidades(Comunidad comunidades) {
	comunidades = comunidades;
}

public ArrayList<Publicacion> getPublicaciones() {
	return publicaciones;
}

public void setPublicaciones(ArrayList<Publicacion> publicaciones) {
	publicaciones = publicaciones;
}

public ArrayList<Comentario> getComentarios() {
	return comentarios;
}

public void setComentarios(ArrayList<Comentario> comentarios) {
	comentarios = comentarios;
}

public ArrayList<Cuenta> getUsuarios() {
	return usuarios;
}

public void setUsuarios(ArrayList<Cuenta> usuarios) {
	usuarios = usuarios;
}

public Factory_Publicacion getFactoryPublicacion() {
	return factoryPublicacion;
}

public void setFactoryPublicacion(Factory_Publicacion factoryPublicacion) {
	factoryPublicacion = factoryPublicacion;
}

  
  /** */
  public void Baja()
  {

	  
  }
  
  /** */
  public void Cambiar_contrasenia(String constrasenia, String nuevaContrasenia)
  {
  
  }
  
  /** */
  public void Login(String alias, String contrasenia)
  {
	 if(alias==this.alias && contrasenia == this.contrasenia)
		 System.out.println("acceso concedido");
  }
  
  /** */
  public void Insertar_datos(String correo, String alias, String contrasenia)
  {
  
  }
  
  /** */
  public void Notificacion_contrasenia_no_coincide()
  {
  
  }
  
  /** */
  public void Notificacion_cuenta_creada_usuario()
  {
  
  }
  
  /** */
  public void InsertarComunidad(Comunidad comunidad)
  {
  
  }
  
  /** */
  public void InsertarPublicacion(Publicacion publicacion)
  {
  
  }
  
  /** */
  public void InsertarComentario(Comentario comentario)
  {
  
  }
  
  /** */
  public void InsertarUsuario(Cuenta usuario)
  {
  
  }
  
  /** */
  public void InsertarFactoryPublicacion(Factory_Publicacion factory)
  {
  
  }
  
  public void EliminarComunidad(Comunidad comunidad)
  {
  
  }
  
  /** */
  public void EliminarPublicacion(Publicacion publicacion)
  {
  
  }
  
  /** */
  public void EliminarComentario(Comentario comentario)
  {
  
  }
  
  /** */
  public void EliminarFactoryPublicacion()
  {
  
  }
}
