import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cuenta.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Cuenta
{
  /** */
  private String Correo;
  
  /** */
  private String Alias;
  
  /** */
  private String Contrasenia;
  
  /** */
  private Comunidad Comunidades;
  
  /** */
  private ArrayList<Publicacion> Publicaciones;
  
  /** */
  private ArrayList<Comentario> Comentarios;
  
  /** */
  private ArrayList<Cuenta> Usuarios;
  
  /** */
  private Factory_Publicacion FactoryPublicacion;
  
  
  
  public String getCorreo() {
	return Correo;
}

public void setCorreo(String correo) {
	Correo = correo;
}

public String getAlias() {
	return Alias;
}

public void setAlias(String alias) {
	Alias = alias;
}

public String getContrasenia() {
	return Contrasenia;
}

public void setContrasenia(String contrasenia) {
	Contrasenia = contrasenia;
}

public Comunidad getComunidades() {
	return Comunidades;
}

public void setComunidades(Comunidad comunidades) {
	Comunidades = comunidades;
}

public ArrayList<Publicacion> getPublicaciones() {
	return Publicaciones;
}

public void setPublicaciones(ArrayList<Publicacion> publicaciones) {
	Publicaciones = publicaciones;
}

public ArrayList<Comentario> getComentarios() {
	return Comentarios;
}

public void setComentarios(ArrayList<Comentario> comentarios) {
	Comentarios = comentarios;
}

public ArrayList<Cuenta> getUsuarios() {
	return Usuarios;
}

public void setUsuarios(ArrayList<Cuenta> usuarios) {
	Usuarios = usuarios;
}

public Factory_Publicacion getFactoryPublicacion() {
	return FactoryPublicacion;
}

public void setFactoryPublicacion(Factory_Publicacion factoryPublicacion) {
	FactoryPublicacion = factoryPublicacion;
}

/** */
  public Cuenta()
  {
  
  }
  
  /** */
  public void Destroy()
  {
  
  }
  
  /** */
  public void Baja()
  {
  
  }
  
  /** */
  public void Cambiar_contrasenia(String constrasenia, String nuevaContrasenia)
  {
  
  }
  
  /** */
  public void Login(String alias, String contrasenia)
  {
	 if(alias==this.Alias && contrasenia == this.Contrasenia)
		 System.out.println("acceso concedido");
  }
  
  /** */
  public void Insertar_datos(String correo, String alias, String contrasenia)
  {
  
  }
  
  /** */
  public void Notificacion_contrasenia_no_coincide()
  {
  
  }
  
  /** */
  public void Notificacion_cuenta_creada_usuario()
  {
  
  }
  
  /** */
  public void InsertarComunidad(Comunidad comunidad)
  {
  
  }
  
  /** */
  public void InsertarPublicacion(Publicacion publicacion)
  {
  
  }
  
  /** */
  public void InsertarComentario(Comentario comentario)
  {
  
  }
  
  /** */
  public void InsertarUsuario(Cuenta usuario)
  {
  
  }
  
  /** */
  public void InsertarFactoryPublicacion(Factory_Publicacion factory)
  {
  
  }
  
  public void EliminarComunidad(Comunidad comunidad)
  {
  
  }
  
  /** */
  public void EliminarPublicacion(Publicacion publicacion)
  {
  
  }
  
  /** */
  public void EliminarComentario(Comentario comentario)
  {
  
  }
  
  /** */
  public void EliminarFactoryPublicacion()
  {
  
  }
}
