//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Factory_Publicacion.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Factory_Publicacion
{
  /** */
  public Publicacion Factory_Method(String Contenido)
  {
	return null;
  
  }
}
