import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gestor_Cuenta.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Gestor_Cuenta
{
  /** */
  private ArrayList<Cuenta> Cuentas;
  
  /** */
  private Servidor_UPM Servidor_UPM;
  
  
  
  
  public ArrayList<Cuenta> getCuentas() {
	return Cuentas;
}

public void setCuentas(ArrayList<Cuenta> cuentas) {
	Cuentas = cuentas;
}

public Servidor_UPM getServidor_UPM() {
	return Servidor_UPM;
}

public void setServidor_UPM(Servidor_UPM servidor_UPM) {
	Servidor_UPM = servidor_UPM;
}

/** */
  public void Login(String Alias, String Contraseña)
  {
  
  }
  
  /** */
  public void Alta(String Alias, String Correo, String Contraseña1, String Contraseña2)
  {
  
  }
  
 
  /** */
  public void RemoveCuenta(Cuenta cuenta)
  {
  
  }
  
  /** */
  public Boolean Comprobar_Correo_Registrado(String correo)
  {
	return null;
  
  }
  
  /** */
  public void Cambiar_Contrasenia(String contrasenia1, String contrasenia2)
  {
  
  }
  
  /** */
  public Gestor_Cuenta()
  {
	  
  }
  
  /** */
  public void Destroy()
  {
  
  }
}
