import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gestor_Cuenta.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Gestor_Cuenta
{
  /** */
  private ArrayList<Cuenta> cuentas;
  
  /** */
  private Servidor_UPM Servidor_UPM;
  
  
  
  /** */
  public Gestor_Cuenta()
  {
	  //se inicializa el array de cuentas
	  cuentas = new ArrayList<Cuenta>();
	  
	  // creamos parseador de JSON
	  JSONParser parser = new JSONParser();
		
		try {
			//abrimos y parseamos el fichero json con el parseador (2 instrucciones)
			Object obj = parser.parse(new FileReader("Usuarios.json"));
			JSONArray users = (JSONArray) obj;
			
			//creamos el iterador para recorrer los usuarios del fichero JSON ya parseado
			Iterator<JSONObject> iter = users.iterator();
			
			//mientras que queden usuarios en el fichero JSON
			while(iter.hasNext()) {
			
				//sacamos un usuario
				JSONObject usuario = (JSONObject) iter.next();
				
				//sacamos todos sus atributos
				String alias = (String) usuario.get("alias");
				String correo = (String) usuario.get("correo");
				String contrasenia = (String) usuario.get("contrasenia");
				ArrayList<Comunidad> comunidades = (ArrayList<Comunidad>) usuario.get("comunidades");
				ArrayList<Publicacion> publicaciones = (ArrayList<Publicacion>) usuario.get("publicaciones");
				ArrayList<Comentario> comentarios = (ArrayList<Comentario>) usuario.get("comentarios");
				ArrayList<Cuenta> usuarios = (ArrayList<Cuenta>) usuario.get("usuarios");
				
				//creamos la cuenta con los atributos del usuario
				Cuenta nueva_cuenta = new Cuenta(alias,correo ,contrasenia ,comunidades ,publicaciones ,comentarios ,usuarios);
				
				//y la añadimos a la coleccion de cuentas
				cuentas.add(nueva_cuenta);
				
			}
			
			
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	  
	  //Servidor_UPM = new Servidor_UPM();
  }
  
  public ArrayList<Cuenta> getCuentas() {
	return cuentas;
}

public void setCuentas(ArrayList<Cuenta> cuentas) {
	this.cuentas = cuentas;
}

public Servidor_UPM getServidor_UPM() {
	return Servidor_UPM;
}

public void setServidor_UPM(Servidor_UPM servidor_UPM) {
	Servidor_UPM = servidor_UPM;
}

/** */
  public void Login(String Alias, String Contraseña)
  {
  
  }
  
  /** */
  public void Alta()
  {
	  //Creamos Directorio root del JSON donde vamos a añadir las cuentas
	  JSONArray lista_usuarios = new JSONArray();
	 
	  //Damos de alta una cuenta
	  cuentas.add(new Cuenta());
	  
	  //Creamos el iterator de cuentas
	  Iterator<Cuenta> iter = cuentas.iterator();
	  
	  //Añadimos todas las cuentas al directorio root del JSON
	  while(iter.hasNext()) {
		 lista_usuarios.add(iter.next().guardarDatos());
	  }
	  
	  //Actualizamos la información en el fichero JSON
	  try(FileWriter file = new FileWriter("Usuarios.json")){
			file.write(lista_usuarios.toJSONString());
		}catch(IOException e) {
			e.printStackTrace();
		}
	  
  }
  
 
  /** */
  public void RemoveCuenta(Cuenta cuenta)
  {
  
  }
  
  /** */
  public Boolean Comprobar_Correo_Registrado(String correo)
  {
	return null;
  
  }
  
  /** */
  public void Cambiar_Contrasenia(String contrasenia1, String contrasenia2)
  {
  
  }
  
  
  /** */
  public void Destroy()
  {
  
  }
}
