//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Comunidad_Admin.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public interface IComunidad_Admin
{
  /** */
  public void Expulsar_Miembro();
  
  /** */
  public void Dar_Permiso_Administrador();
  
  /** */
  public void Quitar_Permiso_Administrador();
  
  /** */
  public void Aceptar_Peticion_Miembro();
  
  /** */
  public void Borrar_Comunidad();
  
  /** */
  public void Notificar_Administrador_Comunidad_Creada();
}
