//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IComentario.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public interface IComentario
{
  /** */
  public void Mostrar();
  
  /** */
  public void SubirComentario();
  
  /** */
  public void Borrar();
}
