//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IComunidad.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public interface IComunidad
{
  /** */
  public void Añadir_Mensaje();
  
  /** */
  public void Mostrar_Mensajes();
}
