//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IEnlace.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public interface IEnlace
{
  /** */
  public void Extraer_Titulo();
  
  /** */
  public void Extraer_Resumen();
  
  /** */
  public void Extraer_Imagen();
  
  /** */
  public void Extraer_Pagina();
}
