//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionCuentasBBDD.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public interface IGestionCuentasBBDD
{
  /** */
  public void InsertCuenta();
  
  /** */
  public void DeleteCuenta();
  
  /** */
  public void SelectCuenta();
}
