//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IPublicacion.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public interface IPublicacion
{
  /** */
  public void MostrarPopularidad();
  
  /** */
  public void Mostrar_Timeline();
  
  /** */
  public void Mostrar();
  
  /** */
  public void Borrar();
  
  /** */
  public void VotarPositivo();
  
  /** */
  public void VotarNegativo();

}
