//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IServidor_UPM.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public interface IServidor_UPM
{
  /** */
  public void Verificar_Correo_UPM();
}
