//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Publicacion_texto.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Publicacion_texto extends Publicacion
{
}
