import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Publicacion.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Publicacion implements IPublicacion
{
  /** */
  private String Contenido;
  
  /** */
  private int Upvotes;
  
  /** */
  private int Downvotes;
  
  /** */
  private ArrayList<Comentario> Comentarios;
  
  
  
  
  public String getContenido() {
	return Contenido;
}

public void setContenido(String contenido) {
	Contenido = contenido;
}

public int getUpvotes() {
	return Upvotes;
}

public void setUpvotes(int upvotes) {
	Upvotes = upvotes;
}

public int getDownvotes() {
	return Downvotes;
}

public void setDownvotes(int downvotes) {
	Downvotes = downvotes;
}

public ArrayList<Comentario> getComentarios() {
	return Comentarios;
}

public void setComentarios(ArrayList<Comentario> comentarios) {
	Comentarios = comentarios;
}

/** */
  public Publicacion()
  {
  
  }
  
  /** */
  public void Destroy()
  {
  
  }
  
  
  /** */
  public void Borrar()
  {
  
  }
  
  /** */
  public void Mostrar()
  {
  
  }
  
  /** */
  public void Mostrar_Timeline()
  {
  
  }
  
  /** */
  public void Mostrar_Popularidad()
  {
  
  }
  
  /** */
  public void VotarPositivo()
  {
  
  }
  
  /** */
  public void VotarNegativo()
  {
  
  }
  
  /** */
  public void Comprobar_Numero_Caracteres()
  {
  
  }
  
  /** */
  public void Insertar_Contenido()
  {
  
  }
  
  /** */
  public void Notificacion_excede_numero_caracteres()
  {
  
  }
  
  /** */
  public void AñadirComentario(Comentario comentario)
  {
  
  }

  
  /** */
  public void BorradoCascadaComentarios()
  {
  
  }

@Override
public void MostrarPopularidad() {
	// TODO Auto-generated method stub
	
}
}
