import java.util.ArrayList;
import java.util.Scanner;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Publicacion.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Publicacion implements IPublicacion
{
	
  Scanner scan = new Scanner(System.in);
  /** */
  private String contenido;
  
  /** */
  private int upvotes;
  
  /** */
  private int downvotes;
  
  /** */
  private ArrayList<Comentario> comentarios;
  
  /** */
  public Publicacion()
  {
	  System.out.println("¿Qué quieres contar al mundo? :");
	  this.contenido = scan.nextLine();
	  System.out.println(contenido);
	  this.upvotes = 0;
	  this.downvotes = 0;
	  this.comentarios = new ArrayList<Comentario>();
  }
  
  
  public String getContenido() {
	return contenido;
}

public void setContenido(String contenido) {
	this.contenido = contenido;
}

public int getUpvotes() {
	return upvotes;
}

public void setUpvotes(int upvotes) {
	this.upvotes = upvotes;
}

public int getDownvotes() {
	return downvotes;
}

public void setDownvotes(int downvotes) {
	this.downvotes = downvotes;
}

public ArrayList<Comentario> getComentarios() {
	return comentarios;
}

public void setComentarios(ArrayList<Comentario> comentarios) {
	this.comentarios = comentarios;
}


  
  /** */
  public void Borrar()
  {
  
  }
  
  @Override
  public String toString() {
	  return this.contenido + "" + upvotes + "	" + downvotes /*+ comentarios*/;
   }
  
  /** */
  public void Mostrar()
  {
	  System.out.println(toString());
  }
  
  /** */
  public void Mostrar_Timeline()
  {
	  
  }
  
  /** */
  public void Mostrar_Popularidad()
  {
	  
  }
  
  /** */
  public void VotarPositivo()
  {
	  this.upvotes++;
  }
  
  /** */
  public void VotarNegativo()
  {
	  this.downvotes--;
  }
  
  /** */
  public boolean Comprobar_Numero_Caracteres()
  {
	  boolean result = false;
	  if(this.contenido.length() > 140)
		  result = true;
	  return result;
  }
  
  /** */
  public void Insertar_Contenido()
  {
	  System.out.println("¿Qué quieres contar al mundo? :");
	  this.contenido = scan.nextLine();
  }
  
  /** */
  public void Notificacion_excede_numero_caracteres()
  {
	  
  }
  
  /** */
  public void AñadirComentario(Comentario comentario)
  {
	  
  }

  
  /** */
  public void BorradoCascadaComentarios()
  {
  
  }

@Override
public void MostrarPopularidad() {
	// TODO Auto-generated method stub
	
}
}
