//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Publicacion_referencia.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Publicacion_referencia extends Publicacion
{
  /** */
  private Publicacion_texto Referencia;
  
  
  
  public Publicacion_texto getReferencia() {
	return Referencia;
}



public void setReferencia(Publicacion_texto referencia) {
	Referencia = referencia;
}



/** */
  public void EliminarReferencia()
  {
  
  }
}
