//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Servidor_UPM.java
//  @ Date : 30/05/2019
//  @ Author : 
//
//




/** */
public class Servidor_UPM implements IServidor_UPM
{
  /** */
  private Gestor_Cuenta Comprobar_correo_cuenta;
  
  /** */
  private Gestor_Cuenta Gestor_Cuenta;
  
  /** */
  public void Verificar_Correo_UPM()
  {
  
  }

public Gestor_Cuenta getComprobar_correo_cuenta() {
	return Comprobar_correo_cuenta;
}

public void setComprobar_correo_cuenta(Gestor_Cuenta comprobar_correo_cuenta) {
	Comprobar_correo_cuenta = comprobar_correo_cuenta;
}

public Gestor_Cuenta getGestor_Cuenta() {
	return Gestor_Cuenta;
}

public void setGestor_Cuenta(Gestor_Cuenta gestor_Cuenta) {
	Gestor_Cuenta = gestor_Cuenta;
}
}
